# Generated by Django 5.2.14 on 2026-05-19 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('WORK_INJURY', 'Work-Related Injury'), ('ROUTINE_ILLNESS', 'General Illness (Malaria, Typhoid, etc.)'), ('EXPOSURE', 'Chemical/Bio-Product Exposure'), ('FITNESS_CHECK', 'Routine Medical Fitness Clearance')], max_length=30)),
                ('incident_date', models.DateField(default=django.utils.timezone.now, help_text='Date illness reported or injury occurred')),
                ('chief_complaint', models.CharField(help_text='Summary of what the staff is experiencing or the injury', max_length=250)),
                ('clinical_notes', models.TextField(blank=True, help_text='Symptoms, diagnosis details, or incident description', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Under Observation / Active Case'), ('SICK_LEAVE', 'On Approved Sick Leave'), ('RESOLVED', 'Fit for Duty / Resolved')], default='OPEN', max_length=20)),
                ('recommended_sick_days', models.PositiveIntegerField(default=0, help_text='Number of days ordered off-duty by clinician')),
                ('return_to_work_date', models.DateField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffTreatmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('medication_or_first_aid', models.CharField(help_text='Administered drugs, dressings, or clinic referrals', max_length=200)),
                ('dosage_or_action', models.CharField(help_text='e.g., 500mg, Rest, Referred to General Hospital', max_length=100)),
                ('administered_by', models.CharField(help_text='Name of Medical Officer or Safety Warden in charge', max_length=100)),
                ('next_review_date', models.DateField(blank=True, help_text='Follow-up clinical evaluation date if needed', null=True)),
                ('medical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='medical.staffmedicalcase')),
            ],
        ),
    ]
