# Generated by Django 5.2.14 on 2026-05-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storetransaction',
            old_name='type',
            new_name='types',
        ),
    ]
