# Generated by Django 5.2.14 on 2026-05-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_type_storetransaction_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storetransaction',
            old_name='types',
            new_name='transaction_type',
        ),
    ]
