# Generated by Django 5.2.14 on 2026-05-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_types_storetransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransaction',
            name='department',
            field=models.CharField(choices=[('GH', 'Greenhouse'), ('OF', 'Open Field'), ('LS', 'Livestock'), ('AD', 'Admin')], default='GH', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='is_returnable',
            field=models.BooleanField(default=False, help_text='Is this a tool that must be returned?'),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='receiver_name',
            field=models.CharField(help_text='Who is physically taking the item?', max_length=100, null=True),
        ),
    ]
