# Generated by Django 5.2.14 on 2026-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_storetransaction_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransaction',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
