# Generated by Django 5.2.14 on 2026-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_storetransaction_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransaction',
            name='quantity_returned',
            field=models.IntegerField(default=0),
        ),
    ]
