# Generated by Django 5.2.14 on 2026-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_storetransaction_quantity_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TOOL', 'Tool/Equipment (Returnable)'), ('CONS', 'Consumable (Non-Returnable)')], default='TOOL', max_length=4),
        ),
    ]
