# Generated by Django 5.2.14 on 2026-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetransaction',
            name='is_returnable',
            field=models.BooleanField(default=False),
        ),
    ]
