# Generated by Django 5.2.14 on 2026-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_storetransaction_is_returnable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetransaction',
            name='is_returnable',
            field=models.BooleanField(default=False, help_text='Is this a tool that must be returned?'),
        ),
    ]
