# Generated by Django 5.2.14 on 2026-05-19 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_tag', models.CharField(help_text='e.g., Pen 4 Layers, Sow #12, Batch B Broilers', max_length=100)),
                ('animal_type', models.CharField(choices=[('POULTRY', 'Poultry (Poultry/Layers/Broilers)'), ('PIGGERY', 'Piggery'), ('CATTLE', 'Cattle'), ('SMALL_RUM', 'Small Ruminants (Goats/Sheep)'), ('AQUACULTURE', 'Aquaculture (Fish)')], max_length=15)),
                ('stage', models.CharField(choices=[('YOUNG', 'Young / Chicks / Weaners'), ('GROWING', 'Growing / Growers / Fingerlings'), ('MATURE_PROD', 'Mature Production (Layers / Milking)'), ('MATURE_MEAT', 'Mature Fattening (Broilers / Market Size)'), ('BREEDER', 'Breeder Stock')], max_length=15)),
                ('breed', models.CharField(blank=True, help_text='e.g., Kalahari Red, Noiler, Large White', max_length=100)),
                ('initial_count', models.IntegerField(default=1)),
                ('current_count', models.IntegerField(default=1, help_text='Auto-updates based on mortalities/sales')),
                ('housing_location', models.CharField(help_text='e.g., Pen 2, Coop A, Paddock 5', max_length=100)),
                ('date_acquired', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if the batch is completely sold or processed')),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('yield_type', models.CharField(choices=[('EGGS', 'Eggs (Crates)'), ('MILK', 'Milk (Liters)'), ('MEAT', 'Live Weight Sold (kg)'), ('MANURE', 'Manure (Bags)')], max_length=10)),
                ('quantity_good', models.DecimalField(decimal_places=2, help_text='Main sellable yield count', max_digits=7)),
                ('quantity_damaged', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g., cracked eggs, spilled milk', max_digits=5)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_yields', to='livestock.livestockgroup')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mortality', models.IntegerField(default=0, help_text='Number of animal deaths today')),
                ('avg_weight', models.DecimalField(blank=True, decimal_places=2, help_text='In kg (Optional tracker)', max_digits=6, null=True)),
                ('feed_type_used', models.CharField(blank=True, help_text='e.g., Layer Mash, Starter Pellets', max_length=100)),
                ('feed_quantity_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('health_status', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('STABLE', 'Stable'), ('ALERT', 'Sick/Alert')], default='EXCELLENT', max_length=20)),
                ('medication_administered', models.CharField(blank=True, help_text='e.g., Gumboro Vaccine, Tylosin', max_length=150)),
                ('notes', models.TextField(blank=True, help_text='General observations (e.g., wet litter, drop in feed intake)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='livestock.livestockgroup')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('group', 'date')},
            },
        ),
    ]
