# Generated by Django 5.2.14 on 2026-05-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_livestockgroup_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockgroup',
            name='name_or_tag',
            field=models.CharField(help_text='e.g., Pen 4 Layers, Sow #12, Batch B Broilers', max_length=100, unique=True),
        ),
    ]
