# Generated by Django 5.2.14 on 2026-05-16 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('GH1', 'Greenhouse 1 (Bays 1-11)'), ('GH2', 'Greenhouse 2 (Bays 1-12)'), ('OPEN', 'Open Field (1.5 Hectares)')], max_length=5)),
                ('bay_number', models.IntegerField(blank=True, help_text='Leave blank if Open Field', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this space currently usable?')),
            ],
            options={
                'ordering': ['area_type', 'bay_number'],
                'unique_together': {('area_type', 'bay_number')},
            },
        ),
        migrations.CreateModel(
            name='CropBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('TOMATO', 'Tomato'), ('SWEET_PEPPER', 'Sweet Pepper'), ('HABANERO', 'Habanero Pepper'), ('CUCUMBER', 'Cucumber')], max_length=20)),
                ('variety', models.CharField(help_text='e.g., Eva F1, Habanero Red, etc.', max_length=50)),
                ('plant_count', models.IntegerField(help_text='Number of seedlings transplanted')),
                ('transplant_date', models.DateField()),
                ('is_harvested', models.BooleanField(default=False, help_text='Check when the entire lifecycle is completed')),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='greenhouse.productionarea')),
            ],
        ),
        migrations.CreateModel(
            name='SprayingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('application_type', models.CharField(choices=[('PREV', 'Preventative (Routine Schedule)'), ('CURA', 'Curative (Active Outbreak Attack)')], default='PREV', max_length=4)),
                ('remedy_used', models.CharField(help_text='e.g., Neem Oil Extract, Tephrosia Leaf Extract, Wood Ash mixture', max_length=100)),
                ('dosage', models.CharField(help_text='e.g., 50ml per 20L Knapsack', max_length=50)),
                ('target_pest_disease', models.CharField(help_text='e.g., Tuta Absoluta, Whiteflies, Aphids, Downy Mildew', max_length=150)),
                ('observations', models.TextField(blank=True, help_text='Crop response or pest mortality observations', null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprays', to='greenhouse.cropbatch')),
                ('operator', models.ForeignKey(help_text='Who sprayed it?', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
