# Generated by Django 5.2.14 on 2026-05-16 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbatch',
            name='expected_yield_per_plant',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Expected yield in kilograms per plant for this cycle (e.g., 4.00)', max_digits=5),
        ),
        migrations.CreateModel(
            name='HarvestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_harvested', models.DateField()),
                ('quantity_harvested', models.DecimalField(decimal_places=2, help_text='Weight recorded in Kilograms (KG)', max_digits=7)),
                ('grade_a_percentage', models.IntegerField(default=100, help_text='Percentage of premium, market-ready produce (0-100)')),
                ('remarks', models.TextField(blank=True, help_text='e.g., First flush picking, minor blossom end rot noticed', null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='greenhouse.cropbatch')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
