# Generated by Django 5.2.14 on 2026-05-17 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0002_cropbatch_expected_yield_per_plant_harvestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('BEDP', 'Bed Preparation / Soil Amendment'), ('PRUN', 'Pruning / Defoliation / Suckering'), ('STAK', 'Staking / Trellising / Twisting'), ('WEED', 'Weeding / Sanitation'), ('SCOO', 'Scooping (Manual Pest/Debris Removal)'), ('SCOU', 'Pest & Disease Scouting'), ('SPRA', 'Spraying Application Routine'), ('HARV', 'Harvesting Operation'), ('FERT', 'Fertilization / Fertigation'), ('IRRI', 'Irrigation System Maintenance'), ('OTHR', 'Other General Maintenance')], max_length=4)),
                ('description', models.TextField(help_text='Details of work done or observations made (e.g., pruned lower leaves, spotted early whitefly activity)')),
                ('man_hours', models.DecimalField(decimal_places=1, default=1.0, help_text='Estimated hours spent on this task', max_digits=4)),
                ('batch', models.ForeignKey(help_text='Select the crop batch/bay', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='greenhouse.cropbatch')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
